django/AlidhemBridge/AlidhemBridge/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic import TemplateView	

urlpatterns = [
	url(r'^home/', include('home.urls')),
	url(r'^news/', include('news.urls')),
	url(r'^events/', include('events.urls')),
	url(r'^forum/', TemplateView.as_view(template_name="home/construction.html")),
	url(r'^members/', include('members.urls')),
	url(r'^association/', include('association.urls')),
	url(r'^apply/', TemplateView.as_view(template_name="home/construction.html")),
  url(r'^admin/', admin.site.urls),
	
	url(r'^', include('home.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

django/AlidhemBridge/association/urls.py
from django.conf.urls import url

from . import views

app_name = 'association'
urlpatterns = [
    url(r'^$', views.index, name='index'),
		url(r'^about$', views.index, name='about'),
		url(r'^statutes/(?P<statute_id>[0-9]+)/$', views.detail_statute, name='detail_statute'),
		url(r'^boards/(?P<board_id>[0-9]+)/$', views.detail_board, name='detail_board'),
		url(r'^annuals/(?P<annual_id>[0-9]+)/$', views.detail_annual, name='detail_annual'),
		url(r'^motions/(?P<motion_id>[0-9]+)/$', views.detail_motion, name='detail_motion'),
]

django/AlidhemBridge/events/urls.py
from django.conf.urls import url

from . import views

app_name = 'events'
urlpatterns = [
    url(r'^$', views.index, name='index'),
		url(r'^(?P<event_id>[0-9]+)/$', views.detail, name='detail'),
]

django/AlidhemBridge/home/urls.py
from django.conf.urls import url

from . import views

app_name = 'home'
urlpatterns = [
    url(r'^$', views.index, name='index'),
		url(r'^start/$', views.index, name='start'),
		url(r'^faq/$', views.faq, name='faq'),
]

django/AlidhemBridge/members/urls.py
from django.conf.urls import url

from . import views

app_name = 'members'
urlpatterns = [
    url(r'^$', views.index, name='index'),
]

django/AlidhemBridge/news/urls.py
from django.conf.urls import url

from . import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.index, name='index'),
		url(r'^(?P<news_id>[0-9]+)/$', views.detail, name='detail'),
]

django/AlidhemBridge/association/models.py
from django.db import models

class Statute(models.Model):
	date = models.DateField('date')
	document = models.FileField(upload_to='documents/statutes')
	
	def __str__(self):
		return str(self.date)
		
class BoardMeeting(models.Model):
	date = models.DateField('date')
	document = models.FileField(upload_to='documents/board_meetings')
	
	def __str__(self):
		return str(self.date)
		
class Annual(models.Model):
	date = models.DateField('date')
	document = models.FileField(upload_to='documents/annuals')
	
	def __str__(self):
		return str(self.date)
		
class Motion(models.Model):
	date = models.DateField('date')
	document = models.FileField(upload_to='documents/motions')
	
	def __str__(self):
		return str(self.date)

django/AlidhemBridge/events/models.py
from django.db import models

class Event(models.Model):
	date = models.DateTimeField()
	title = models.CharField(max_length=200)
	description = models.TextField()
		
	def __str__(self):
		return str(self.date.date()) + " - " + self.title

django/AlidhemBridge/home/models.py
from django.db import models

# Create your models here.

django/AlidhemBridge/members/models.py
from django.db import models

# Create your models here.

class Member(models.Model):
	first_name = models.CharField(max_length=50)
	last_name = models.CharField(max_length=50, blank=True)
	office = models.CharField(max_length=50, blank=True)
	email = models.EmailField(max_length=100, blank=True)
	portrait = models.FileField(upload_to='member_portraits/', null=True, blank=True)

	def __str__(self):
		return self.first_name + " " + self.last_name

django/AlidhemBridge/news/models.py
from django.db import models

class News(models.Model):
	publish_date = models.DateTimeField('date published')
	author = models.CharField(max_length=50)
	image = models.FileField(upload_to='news_images/')
	title = models.CharField(max_length=200)
	legend = models.CharField(max_length=200)
	ingress = models.TextField()
	body = models.TextField()
	
	class Meta:
		verbose_name_plural = "news"
		
	def __str__(self):
		return str(self.publish_date.date()) + " - " + self.title
	

django/AlidhemBridge/association/views.py
from django.shortcuts import render, get_object_or_404

from .models import Statute, BoardMeeting, Annual, Motion

def index(request):
	context = get_context()
	return render(request, 'association/about.html', context)
	
def detail_statute(request, statute_id):
	statute_detail = get_object_or_404(Statute, pk=statute_id)
	context = get_context()
	context['active'] = statute_detail
	
	return render(request, 'association/document.html', context)
	
def detail_board(request, board_id):
	board_detail = get_object_or_404(BoardMeeting, pk=board_id)
	context = get_context()
	context['active'] = board_detail
	
	return render(request, 'association/document.html', context)
	
def detail_annual(request, annual_id):
	annual_detail = get_object_or_404(Annual, pk=annual_id)
	context = get_context()
	context['active'] = annual_detail
	
	return render(request, 'association/document.html', context)
	
def detail_motion(request, motion_id):
	motion_detail = get_object_or_404(Motion, pk=motion_id)
	context = get_context()
	context['active'] = motion_detail
	
	return render(request, 'association/document.html', context)
	
	
def get_context():
	statutes = Statute.objects.order_by('-date')
	boards = BoardMeeting.objects.order_by('-date')
	annuals = Annual.objects.order_by('-date')
	motions = Motion.objects.order_by('-date')
	
	context = {'statutes':statutes, 'boards':boards, 'annuals':annuals, 'motions':motions}
	return context
	

django/AlidhemBridge/events/views.py
from django.shortcuts import render, get_object_or_404

from .models import Event

def index(request):
	events = Event.objects.order_by('-date')
	context = {'events' : events, 'active' : events.first()}
	return render(request, 'events/events.html', context)
	
def detail(request, event_id):
	event_detail = get_object_or_404(Event, pk=event_id)
	events = Event.objects.order_by('-date')
	context = {'events' : events, 'active' : event_detail}
	return render(request, 'events/events.html', context)

django/AlidhemBridge/home/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'home/start.html')
	
def faq(request):
	return render(request, 'home/faq.html')

django/AlidhemBridge/members/views.py
from django.shortcuts import render
from django.http import HttpResponse

from .models import Member
# Create your views here.

def index(request):
	members = Member.objects.order_by('last_name')
	context = {'members' : members}
	
	return render(request, 'members/members.html', context)

django/AlidhemBridge/news/views.py
from django.shortcuts import render, get_object_or_404

from .models import News

def index(request):
	news = News.objects.order_by('-publish_date')
	context = {'news_list' : news, 'active' : news[0]}
	return render(request, 'news/news.html', context)
	
def detail(request, news_id):
	news_detail = get_object_or_404(News, pk=news_id)
	news = News.objects.order_by('-publish_date')
	context = {'news_list' : news, 'active' : news_detail}
	return render(request, 'news/news.html', context)
	

django/AlidhemBridge/association/templates/association/about.html
{% extends "association/association.html" %}

{% block content %}

<div class="padding">
<h2>OM ÅRSBC</h2>
  <p class="text">
Gemenskap, kamratskap och öppenhet är tre kännetecken för dagens bridgeförening. Föreningen är inte större än sina medlemmars engagemang och den gemytliga stämningen som präglar spelkvällarna är allt tack vare den ungefär 10 personer stora skara som i dagsläget deltar och spelar tillsammans. För att förstå hur vi kommit dit vi befinner oss idag behöver vi gå tillbaka några år i tiden.
  </p>
  <p class="text">
2013 börjar historien om hur ett antal barndomsvänner började ta sina vacklande steg på den bridgebana de befinner sig på idag. En anfader till en av kompisarna hade sedan en tid gått bort och efterlämnade i arv ett antal budbrickor, bridgekortlekar och en nybörjarbok i bridge (denna arvslott utgör än idag ett betydande bidrag för dagens medlemmar).
  </p>
    <p class="text">
Motivet att engagera sina vänner i bridge är, för den anhörige till den bortgångne, antingen bortglömt eller förträngt. Oavsett om det berodde på den efterlevandes skuldkänslor eller en genuin nyfikenhet för bridgens vackra och komplicerade natur så introducerades så småningom kortspelet bridge för vännerna.
    </p>
    <p class="text">
Många historier går att höra från den tiden, tiden före bildandet av föreningen som kommit att förklara hur och varför föreningen uppstått. I början spelade kompisarna bridge med flera månaders mellanrum och det var minst sagt lätt att glömma bort vad de tidigare lärt sig. 2014 och 2015 skedde en långsam upptrappning av hur ofta de träffades för bridgens skull och så småningom kläcktes idén om att starta en egen förening.
    </p>
    <p class="text">
Hösten 2015 grundades Ålidhem royal bridge club då medlemmarna kom att vilja organisera sitt bridgespelande i föreningsform. Grundarnas ambition var att inkludera så många vänner, vänners vänner och vänners vänners vänner som möjligt för att spela bridge på en sällskaplig nivå. I skrivande stund i begynnelsen av 2016 har medlemsantalet fördubblats och antalet personer som provat på bridge tillsammans med oss uppgår till runt 15 personer. Torsdagsbridgen har blivit en stadig företeelse, en hemsida har jobbats fram och föreningen har anslutit sig till Sverok. Vi hoppas på en fortsatt rolig utveckling där vi får lära känna nya personer som vill prova på!
    </p>
    <p class="text">VÄLKOMMEN!</p>
</div>

{% endblock %}

django/AlidhemBridge/association/templates/association/association.html
{% extends "home/base.html" %}

{% load static %}

{% block page %}

<script type="text/javascript" src="{% static 'association/js/association.js' %}"></script>

<div class="sidelinkborder">
	<ul id="side">
		<li> <a class="sidelink title bigtext" href="{% url 'association:about' %}"> Om ÅRSBC </a> </li>
		
		<li id="statutes" class="sidelink"><span class="title bigtext">Stadgar</span></li>
		<ul id="statuteslist" class="hidden clearfix">
			{% for statute in statutes %}
				<li> 
					<a class='sidesublink smalltext' href="{% url 'association:detail_statute' statute.id %}"> {{ statute.date|date:"Y M d" }} </a>
				</li>
			{% endfor %}
		</ul>
		
		<li id="board" class="sidelink"><span class="title bigtext">Styrelsemöte</span></li>
		<ul id="boardlist" class="hidden clearfix">
			{% for board in boards %}
				<li> 
					<a class='sidesublink smalltext' href="{% url 'association:detail_board' board.id %}"> {{ board.date|date:"Y M d" }} </a>
				</li>
			{% endfor %}
		</ul>
		
		<li id="annual" class="sidelink"><span class="title bigtext">Årsmöte</span></li>
		<ul id="annuallist" class="hidden clearfix">
			{% for annual in annuals %}
				<li> 
					<a class='sidesublink smalltext' href="{% url 'association:detail_annual' annual.id %}"> {{ annual.date|date:"Y M d" }} </a>
				</li>
			{% endfor %}
		</ul>
			
		<li id="motion" class="sidelink"><span class="title bigtext">Motion</span></li>
		<ul id="motionlist" class="hidden clearfix">
			{% for motion in motions %}
				<li> 
					<a class='sidesublink smalltext' href="{% url 'association:detail_motion' motion.id %}"> {{ motion.date|date:"Y M d" }} </a>
				</li>
			{% endfor %}
		</ul>
		
	</ul>
</div>

<div class="double" id="content">
	{% block content %} {% endblock %}
</div>

{% endblock %}

django/AlidhemBridge/association/templates/association/document.html
{% extends "association/association.html" %}

{% block content %}

<object type='application/pdf' width='100%' height='800px' data="{{ active.document.url }}" internalinstanceid='223' title=''></object>

{% endblock %}

django/AlidhemBridge/events/templates/events/events.html
{% extends "home/base.html" %}

{% load static %}

{% block page %}

{% if events %}

<div class="sidelinkborder">
  <ul id="side">
		{% for event in events %}
		<a class="sidelink {% if event.id == active.id %} active {% endif %}" href="{% url 'events:detail' event.id %}">
		
		<span class="title bigtext"> {{ event.title }} </span>
	  <span class="date smalltext"> {{ event.date|date:"Y M d" }}</span>
 	  <span class="time smalltext"> {{ event.date|date:"H:i" }} </span>
		
		</a>
		{% endfor %}
	</ul>
</div>

<div class="double" id="content">
	<div class="padding">
		<h2> {{ active.title }} </h2>
		<p class="news-free-text"> {{ active.description }} </p>
	</div>
</div>

{% else %}
	<span class="center">
		<h2> Inga kommande evenemang </h2>
		<figure>
			<img width="25%" src="{% static 'home/img/arsbc.svg' %}">
		</figure>
	</span>
{% endif %}

{% endblock %}

django/AlidhemBridge/home/templates/home/base.html
{% load static %}

<head>

	<link rel="stylesheet" type="text/css" href="{% static 'home/style.css' %}" />
	
	<!-- Icon -->
	<link rel="shortcut icon" type="image/svg" href="{% static 'home/img/arsbc.svg' %}"/>
	
	<script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
	
</head>

<body class="main">

	<div class="main">
	
		<div id="head">
			<div id="logo"><img src="{% static 'home/img/arsbc.svg' %}" /></div>
			<div id="name">
				<div class="top">ÅLIDHEM</div>
				<div class="middle left">ROYAL</div>
				<div class="middle right">STRAIGHT</div>
				<div class="low left clear">BRIDGE</div>
				<div class="low right">CLUB</div>
			</div>
		</div>

		<ul id="headMenu">
			<a href="{% url 'home:index' %}">Hem</a>
			<a href="{% url 'news:index' %}">Nyheter</a>
			<a href="{% url 'events:index' %}">Evenemang</a>
			<a href="/forum/">Inlägg</a>
			<a href="{% url 'members:index' %}"> Medlemmar</a>
			<a href="{% url 'association:index' %}">Förening</a>
			<a href="/apply/">Bli medlem</a>
		</ul>
	  
	  <div id="page">
			{% block page %}{% endblock %}
	  </div>
	</div>

	<div id="foot" class="main">
		<h2> ÅLIDHEM ROYAL STRAIGHT BRIDGE CLUB </h2>
	</div>

</body>

django/AlidhemBridge/home/templates/home/construction.html
{% extends "home/base.html" %}

{% load static %}

{% block page %}

<span class="center">
	<h2> Under konstruktion, vi ska bara... (spela klart handen) </h2>
	<figure>
		<img width="40%" src="{% static 'home/img/keep_calm_play_bridge.jpg' %}">
	</figure>
</span>

{% endblock %}

django/AlidhemBridge/home/templates/home/faq.html
{% extends "home/home.html" %}

{% block content %}

	<div class="padding">
	<h2>VANLIGA FRÅGOR</h2>
			<div class="ingress">
	Är bridge svårt?
			</div>
			<p class="text">Så fort du lärt dig grundreglerna i bridge är det fritt fram att prova sig fram. Vi spelar på en rätt enkel nivå och anpassar oss alltid efter närvarandes erfarenhet. Det är ett spel med många dimensioner och du kan alltid utvecklas.
			</p>

			<div class="ingress">
	Behöver jag några förkunskaper?
			</div>
			<p class="text">
	Nej, vår erfarenhet säger att lättaste sättet att lära sig är att komma och prova på.
			</p>

			<div class="ingress" lang="sv">
	Hur går det till?
			</div>
			<p class="text">
	Spelet går ut på att man tillsammans med en partner i sitt lag ska vinna så många stick som möjligt. En omgång är uppdelat i två faser. Dels en budgivning där lagen försöker uppskatta hur många stick de kommer ta och om de vill spela med trumf eller inte. Dels så spelar man efter att budgivningen har genomförts och bägge lagen försöker ta så många stick som möjligt.
			</p>
			
	</div>

{% endblock %}

django/AlidhemBridge/home/templates/home/home.html
{% extends "home/base.html" %}

{% block page %}

	<ul class="submenu">
		<a href="{% url 'home:start' %}">Start</a>
		<a href="{% url 'home:faq' %}">Vanliga frågor</a>
		<a >Om ÅRSBC</a>
		<a >Brickor</a>
	</ul>

	<div class="single" id="content">
		{% block content %} {% endblock %}
	</div>

	<div id="board"></div>

{% endblock %}

django/AlidhemBridge/home/templates/home/start.html
{% extends "home/home.html" %}

{% block content %}
	<div class="padding">
		<h2>VÄLKOMMEN</h2>
		<div class="ingress">
	Ålidhem royal straight bridge club är en öppen bridgeförening. Vi strävar efter att anordna spelkvällar en gång i veckan. Den så kallade torsdagsbridgen har kommit att bli en omtyckt rutin.
		</div>

		<h2>VAD ÄR TORSDAGSBRIDGE?</h2>
		<p class="text">
	Traditionen har blivit att vi ses på kvällen och äter gemensam middag, avnjuter en kopp kaffe och en bit fika innan vi börjar spela bridge. Kvällarna anordnas oftast hemma hos någon eller i en kvarterslokal på Ålidhem. Hör av dig till någon i föreningen om du är intresserad att prova på!
		</p>

		<h2>HEMSIDESPROJEKT</h2>
		<p class="text">
	Just nu jobbar vi på att införa en konstruerad budgivningssimulering på hemsidan där besökarna veckovis kan jämföra egna beslut med hur andra resonerar i samma situation. Dessutom hoppas vi kunna införa en chatt eller ett forum på hemsidan strax. Till sist strävar vi även efter att införa information om budgivningsstandarden som vi använder på Ålidhem.
		</p>
	</div>
{% endblock %}

django/AlidhemBridge/members/templates/members/members.html
{% extends "home/base.html" %}

{% load static %}

{% block page %}

<div class="single" id="content">

    <h2>Medlemmar</h2>
	{% for member in members %}
    
    <div style="border:3px groove; padding:0px 10px 30px 10px; margin:10px auto; width:70%">
      <figure>
        <img style="width:13%; float:right" src="
			{% if member.portrait %} 
				{{ member.portrait.url }}
			{% else %}
				{% static 'home/img/arsbc.svg' %}
			{% endif %}"
		>
      </figure>

      <div style="text-align:justify; clear:left; width:100%">
        <div style="float:left; width:20%">Namn</div>
        <div style="float:left; width:40%">{{ member.first_name }} {{ member.last_name}}</div>
      </div>
      <div style="text-align:justify; clear:left; width:100%">
        <div style="float:left; width:20%">Uppdrag</div>
        <div style="float:left; width:40%">{{ member.office }}</div>
      </div>
      <div style="text-align:justify; clear:left; width:100%">
        <div style="float:left; width:20%">Email</div>
        <div style="float:left; width:40%">
			{% if member.email %} 
				{{ member.email }}
			{% else %}
				medlem@alidhembridge.se
			{% endif %}
		</div>
      </div>
    </div>

	{% endfor %}

</div>


{% endblock %}

django/AlidhemBridge/news/templates/news/news.html
{% extends "home/base.html" %}

{% load static %}

{% block page %}

<div class="sidelinkborder">
  <ul id="side">
		{% for news in news_list %}
		<a class="sidelink {% if news.id == active.id %} active {% endif %}" href="{% url 'news:detail' news.id %}">
		
		<span class="title bigtext"> {{ news.title }} </span>
	  <span class="date smalltext"> {{ news.publish_date|date:"Y M d" }}</span>
 	  <span class="time smalltext"> {{ news.publish_date|date:"H:i" }} </span>
		
		</a>
		{% endfor %}
	</ul>
</div>

<div class="double" id="content">
	<div class="padding">
		<h2> {{ active.title }} </h2>
		<div class="ingress"><p> {{ active.ingress }} </p></div>
	
		<figure class="newsimage">
			<img width="100%" src="
			{% if active.image %} 
				{{ active.image.url }}
			{% else %}
				{% static 'home/img/arsbc.svg' %}
			{% endif %}">
			<figcaption>{{ active.legend }}</figcaption>
		</figure>
	
		<p class="news-free-text"> {{ active.body }} </p>
	</div>
</div>

{% endblock %}